version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 1
  ignore:
  - dependency-name: nextcloud/ocp
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 1
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
