filter:
        excluded_paths:
                - 'js/*'
                - 'templates/*'
                - 'l10n/*'
                - 'tests/*'

build:
        nodes:
                analysis:
                        tests:
                                override:
                                        - php-scrutinizer-run
                                        - phpcs-run --standard=phpcs.xml appinfo/ lib/
                                        - eslint-run --ext .js,.vue src

tools:
        external_code_coverage: false
        js_hint: false
